FROM golang:1.26.2-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app ./cmd/api

# Prod
FROM alpine:latest
RUN addgroup -g 1000 app && adduser -D -u 1000 -G app app
COPY --from=builder /app /app
USER app
ENTRYPOINT ["/app"]